### ISSUE TITLE
The latest version(0.3.1) cause a lot of type convert error while compiling

### ISSUE THREAD

**Issue by simpleton** [trello/RxLifecycle#63] opened 2015-12-03 22:54 UTC
It works well in version 0.3.0.
Here is my code snippet:
```java
 feedService.getTopicFeedList(groupId, loadPage)
            .compose(this.bindToLifecycle())
            .subscribe(
                feedDetails -> {
                    BannerFeedsAdapter adapter = (BannerFeedsAdapter) recyclerView.getAdapter();
                    if (adapter == null) {
                        adapter = new BannerFeedsAdapter(BannerFeedsActivity.this, feedDetails, bannerUrl, isContainBanner);
                        recyclerView.setAdapter(adapter);
                    } else {
                        adapter.append(feedDetails);
                        adapter.notifyDataSetChanged();
                    }
                    bannerImg.setVisibility(View.GONE);
                },
                throwable -> RxUtil.handleError(throwable, BannerFeedsActivity.this)
            );
```

The type of `feedDetails` is `Object` when I use the 0.3.1 version library.

**Comment by damianflannery** [comment] 2015-12-03 23:09
+1.  I reverted back to 0.3.0 because of this.

**Comment by dlew** [comment] 2015-12-04 00:24
Duplicate of #58, it's been reverted for the next release (whenever that happens, probably soon).

Using 0.3.0 in the meantime fine, since the generics is all that changed.

**Closed by dlew** 2015-12-04 00:24 UTC
