### ISSUE TITLE
What are the thoughts on Application.registerActivityLifecycleCallbacks?

### ISSUE THREAD

**Issue by Laimiux** [trello/RxLifecycle#104] opened 2016-04-12 04:31 UTC
Using this method to tap into Activity lifecycle would avoid having to extend a specific activity implementation like RxAppCompatActivity. Any particular reasons not to use it?

**Comment by dlew** [comment] 2016-04-12 13:28
This is a duplicate of #93 - reasons for not engaging yet are explained there. I'll put some more current thoughts there as well.

**Closed by dlew** 2016-04-12 13:28 UTC
