### ISSUE TITLE
Method bindToLifecycle() works incorrectly.

### ISSUE THREAD

**Issue by m4xp1** [trello/RxLifecycle#224] opened 2017-06-17 13:17 UTC
Method bindToLifecycle() works incorrectly. In the code below action onComplete must be called in
onDestroy() fragment lifecycle. But this is not so, the completion is called at random time. But if you use provider.bindUntilEvent(FragmentEvent.DESTROY) the it works correctly. Why is this happening? These calls must be equivalent.

```
public class MyFragment extends NaviFragment {
    protected final LifecycleProvider<FragmentEvent> provider
            = NaviLifecycle.createFragmentLifecycleProvider(this);

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
        
        Observable.interval(1000, TimeUnit.MILLISECONDS)
                .compose(provider.bindToLifecycle())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(
                        l -> Log.d("TEST", "next = " + l),
                        Throwable::printStackTrace,
                        () -> Log.d("TEST", "onComplete"));
    }
}
```

**Comment by dlew** [comment] 2017-06-19 13:38
What happens if you switch the order of `compose()` and `observeOn()`?

**Comment by atfox7** [comment] 2017-06-28 19:25
We ran into this same issue as well. Using bindUntilEvent did not change the results though for us. Switching the order of compose() and observeOn does work however.

**Comment by shakil807g** [comment] 2017-07-22 10:11
does .compose(provider.bindToLifecycle())   line need to call above subscribe  in order to work correctly ???

**Comment by jaychang0917** [comment] 2017-08-06 03:51
Same problem. The following code doesn't print out `dispose` when `onStop()` is called.
```java
class MainActivity : LifecycleActivity() {

  val provider : LifecycleProvider<Lifecycle.Event> = AndroidLifecycle.createLifecycleProvider(this)

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
  }

  override fun onStart() {
    super.onStart()
    Observable.interval(0, 1, TimeUnit.SECONDS)
      .doOnDispose { println("dispose") }
      .compose(provider.bindToLifecycle())
      .subscribe {
        println("emiit:" + it)
      }
  }

  override fun onStop() {
    super.onStop()
    println("onStop")
  }
  
}
```

**Comment by micHar** [comment] 2019-03-10 06:57
Just had the same situation where I had to put observeOn BEFORE bindToLifecycle, otherwise it randomly crashed (because it didn't close the stream properly upon destroy). Why does it happen?

**Comment by micHar** [comment] 2019-04-03 09:02
To be more specific.

This sometimes doesn't unsubscribe which can result in crashes:
```
...observeWhatevs()
                .bindToLifecycle(viewLifecycleOwner)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe { ... }
```

This works without issues:
```
...observeWhatevs()
                .observeOn(AndroidSchedulers.mainThread())
                .bindToLifecycle(viewLifecycleOwner)
                .subscribe { ... }
```

I could observe this randomly in a situation where I rapidly replaced fragments one after another. The issue was 100% reproducible when (1) I had a fragment which started observing `onViewCreated`, (2) then moved to a different activity (not sure it this step is necessary, but it was present in my case), (3) changed app to night mode (which causes lifecycle recreation), (4) returned to the original activity with the aforementioned fragment. It crashed on some view being null in the `subscribe{}` section.

**Comment by dlew** [comment] 2020-05-23 17:47
Closing because them's the breaks with RxLifecycle (and why I suggest people move to something like AutoDispose). The order of `bindToLifecycle()` matters, and that's a problem, but there's no real way to reconfigure the library to fix that now.

**Closed by dlew** 2020-05-23 17:47 UTC
